spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loan_service?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: loan-service

logging:
  level:
    com:
      billit: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


feign:
  client:
    config:
      default:
        loggerLevel: full
        decode404: true