spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loan_service?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com:
      billit: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8083

feign:
  client:
    config:
      default:
        loggerLevel: full
        decode404: true